# -*- coding: utf-8 -*-
"""
token_names_ar.py

Maps ANTLR token symbolic names (ArabicHtmlLexer.symbolicNames / the
class-attribute integer constants) to the Arabic text that should appear
in a syntax-error message, e.g.:

    "مفقود ؛ قبل '}'"     (missing ';' before '}')

Two sections:

1. TOKEN_DISPLAY_AR_GENERATED — every lexer rule in Grammar.md that is a
   plain literal, or a small set of literal alternatives (e.g.
   TS_ELSE : 'الا' | 'والا' ;). This was machine-extracted directly from
   Grammar.md's lexer section, not retyped by hand, specifically so it
   can't silently drift from the grammar. Verified to cover 251 of the
   261 token types defined in ArabicHtmlLexer.py.

2. TOKEN_DISPLAY_AR_STRUCTURAL — the remaining 10 tokens that have no
   single fixed literal because they're built from character classes
   or fragments (CLOSE_TAG, OPEN_TAG_START, IDENTIFIER, NUMBER,
   CSS_UNIT, CSS_HEX_COLOR, STRING), plus WS/comment/EOF tokens that
   should basically never appear in a real "expecting" clause but get
   a safe description anyway so a lookup never raises.

TOKEN_DISPLAY_AR is the merged dict everything else imports.

NOTE: most syntax-error literals (e.g. '؛', '@وسائط', 'عرض') already
come through correctly from ANTLR's own literalNames array, since this
grammar's literals ARE Arabic text. This map is only consulted for
tokens that have no fixed literal at all (see syntax_error_listener.py's
_translate_token_piece). It is NOT used to re-translate every token —
only the structural/no-literal ones.
"""

TOKEN_DISPLAY_AR_GENERATED = {
    'ATTR_CLASS': "'صنف'",
    'ATTR_HREF': "'وجهة'",
    'ATTR_ID': "'معرف'",
    'ATTR_SRC': "'مصدر'",
    'BANG': "'!'",
    'COLON': "':'",
    'COMMA': "'،'",
    'CSS_ABSOLUTE': "'مطلق'",
    'CSS_ACTIVE': "'نشط'",
    'CSS_AFTER': "'بعد'",
    'CSS_ALIGN_ITEMS': "'محاذاة-العناصر'",
    'CSS_ALIGN_SELF': "'محاذاة-ذاتية'",
    'CSS_AUTO': "'تلقائي'",
    'CSS_BACKDROP_FILT': "'مرشح-الخلفية'",
    'CSS_BACKGROUND': "'خلفية'",
    'CSS_BEFORE': "'قبل'",
    'CSS_BG_ATTACH': "'تثبيت-الخلفية'",
    'CSS_BG_CLIP': "'قص-الخلفية'",
    'CSS_BG_COLOR': "'لون-الخلفية'",
    'CSS_BG_IMAGE': "'صورة-الخلفية'",
    'CSS_BG_REPEAT': "'تكرار-الخلفية'",
    'CSS_BG_SIZE': "'حجم-الخلفية'",
    'CSS_BLOCK': "'كتلة'",
    'CSS_BLUR_FUNC': "'تغبيش'",
    'CSS_BOLD': "'عريض'",
    'CSS_BORDER': "'اطار'",
    'CSS_BORDER_COLLAPSE': "'دمج-الحدود'",
    'CSS_BORDER_COLOR': "'لون-الاطار'",
    'CSS_BORDER_RADIUS': "'انحناء-الاطار'",
    'CSS_BORDER_STYLE': "'نمط-الاطار'",
    'CSS_BORDER_WIDTH': "'سمك-الاطار'",
    'CSS_BOTTOM': "'اسفل'",
    'CSS_BOX_SHADOW': "'ظل-الصندوق'",
    'CSS_BOX_SIZING': "'تحجيم-الصندوق'",
    'CSS_CALC_FUNC': "'حساب'",
    'CSS_CAPTION_SIDE': "'مكان-العنوان'",
    'CSS_CENTER': "'مركز'",
    'CSS_CHECKED': "'محدد'",
    'CSS_COLOR': "'لون'",
    'CSS_COLUMN': "'عمود'",
    'CSS_DASHED': "'مقطع'",
    'CSS_DIRECTION': "'اتجاه-الكتابة'",
    'CSS_DISABLED': "'معطل'",
    'CSS_DISPLAY': "'عرض'",
    'CSS_DOTTED': "'منقط'",
    'CSS_DOUBLE': "'مزدوج'",
    'CSS_ENABLED': "'مفعل'",
    'CSS_FILTER': "'مرشح'",
    'CSS_FIXED': "'مثبت'",
    'CSS_FLEX': "'مرن'",
    'CSS_FLEX_DIR': "'اتجاه-المرونة'",
    'CSS_FLEX_GROW': "'نمو-المرونة'",
    'CSS_FLEX_SHRINK': "'انكماش-المرونة'",
    'CSS_FLEX_VALUE': "'مرونة'",
    'CSS_FLEX_WRAP': "'لف-المرونة'",
    'CSS_FOCUS': "'تركيز'",
    'CSS_FONT_FAMILY': "'نوع-الخط'",
    'CSS_FONT_SIZE': "'حجم-الخط'",
    'CSS_FONT_STYLE': "'نمط-الخط'",
    'CSS_FONT_WEIGHT': "'ثقل-الخط'",
    'CSS_GAP': "'فجوة'",
    'CSS_GRID': "'شبكة'",
    'CSS_GRID_TEMPLATE': "'قالب-الشبكة'",
    'CSS_HEIGHT': "'طول-المساحة'",
    'CSS_HIDDEN': "'مخفي'",
    'CSS_HOVER': "'حوم'",
    'CSS_IMPORTANT': "'هام'",
    'CSS_INHERIT': "'وراثة'",
    'CSS_INITIAL': "'اولي'",
    'CSS_INLINE': "'سطري'",
    'CSS_ITALIC': "'مائل'",
    'CSS_JUSTIFY_CONT': "'ضبط-المحتوى'",
    'CSS_LEFT': "'يسار'",
    'CSS_LETTER_SPACING': "'تباعد-الاحرف'",
    'CSS_LINE_HEIGHT': "'ارتفاع-السطر'",
    'CSS_LIST_STYLE': "'نمط-القائمة'",
    'CSS_MARGIN': "'هامش'",
    'CSS_MAX_HEIGHT': "'اقصى-طول'",
    'CSS_MAX_WIDTH': "'اقصى-عرض'",
    'CSS_MEDIA': "'@وسائط'",
    'CSS_MIN_HEIGHT': "'اقل-طول'",
    'CSS_MIN_WIDTH': "'اقل-عرض'",
    'CSS_NONE': "'لا-شيء'",
    'CSS_OPACITY': "'شفافية'",
    'CSS_ORDER': "'ترتيب'",
    'CSS_OUTLINE': "'خط-خارجي'",
    'CSS_OVERFLOW': "'فائض'",
    'CSS_PADDING': "'حشو'",
    'CSS_PLACEHOLDER': "'نص-مؤقت'",
    'CSS_POINTER': "'مؤشر'",
    'CSS_POSITION': "'موقع'",
    'CSS_RELATIVE': "'نسبي'",
    'CSS_RGBA_FUNC': "'نظام-ر-ج-ب-ا'",
    'CSS_RGB_FUNC': "'نظام-ر-ج-ب'",
    'CSS_RIGHT': "'يمين'",
    'CSS_ROTATE_FUNC': "'تدوير'",
    'CSS_ROW': "'سطر'",
    'CSS_SCALE_FUNC': "'تكبير'",
    'CSS_SELECTION': "'تحديد'",
    'CSS_SOLID': "'متصل'",
    'CSS_STICKY': "'لاصق'",
    'CSS_TABLE_LAYOUT': "'تنسيق-الجدول'",
    'CSS_TEXT_ALIGN': "'محاذاة-النص'",
    'CSS_TEXT_DECOR': "'زخرفة-النص'",
    'CSS_TEXT_INDENT': "'ازاحة-النص'",
    'CSS_TEXT_SHADOW': "'ظل-النص'",
    'CSS_TEXT_TRANS': "'تحويل-النص'",
    'CSS_TOP': "'اعلى'",
    'CSS_UNSET': "'غير-محدد'",
    'CSS_URL_FUNC': "'رابط'",
    'CSS_VAR_FUNC': "'دالة-متغير'",
    'CSS_VISIBILITY': "'الظهور'",
    'CSS_VISITED': "'تم-زيارته'",
    'CSS_WHITE_SPACE': "'المساحة-البيضاء'",
    'CSS_WIDTH': "'عرض-المساحة'",
    'CSS_WORD_SPACING': "'تباعد-الكلمات'",
    'CSS_WRAP': "'لف'",
    'CSS_WRITING_MODE': "'نمط-الكتابة'",
    'CSS_Z_INDEX': "'ترتيب-العمق'",
    'DBL_COLON': "'::'",
    'DOT': "'.'",
    'GT': "'>'",
    'HASH': "'#'",
    'LBRACE': "'{'",
    'LBRACK': "'['",
    'LPAREN': "'('",
    'LT': "'<'",
    'MINUS': "'-'",
    'PERCENT': "'%'",
    'PLUS': "'+'",
    'RBRACE': "'}'",
    'RBRACK': "']'",
    'RPAREN': "')'",
    'SELF_CLOSE_END': "'/>'",
    'SEMI': "'؛'",
    'SLASH': "'/'",
    'STAR': "'*'",
    'TILDE': "'~'",
    'TS_ADD_ASSIGN': "'+='",
    'TS_ADD_LISTENER': "'عند-الحدث' / 'استمع-للحدث'",
    'TS_ALERT': "'تنبيه'",
    'TS_AND': "'&&'",
    'TS_AND_ASSIGN': "'&&='",
    'TS_ANY_KW': "'اي'",
    'TS_ARRAY_KW': "'مصفوفة'",
    'TS_ARROW': "'=>'",
    'TS_AS': "'كما'",
    'TS_ASSIGN': "'='",
    'TS_BIGINT_KW': "'رقم-كبير'",
    'TS_BIT_AND': "'&'",
    'TS_BIT_OR': "'|'",
    'TS_BIT_XOR': "'^'",
    'TS_BOOLEAN_KW': "'منطقي'",
    'TS_BREAK': "'ايقاف'",
    'TS_CASE': "'حالة'",
    'TS_CATCH': "'امسك'",
    'TS_CLASS': "'فئة' / 'صف'",
    'TS_CONSOLE': "'المراقب'",
    'TS_CONST': "'ثابت'",
    'TS_CONSTRUCTOR': "'منشئ'",
    'TS_CONTINUE': "'تجاوز'",
    'TS_CREATE_EL': "'انشئ-عنصر'",
    'TS_DATE_KW': "'تاريخ'",
    'TS_DEC': "'--'",
    'TS_DEFAULT': "'بشكل-افتراضي'",
    'TS_DELETE': "'احذف'",
    'TS_DIV_ASSIGN': "'/='",
    'TS_DO': "'نفذ'",
    'TS_DOCUMENT': "'الوثيقة'",
    'TS_ELEMENT': "'عنصر'",
    'TS_ELSE': "'الا' / 'والا'",
    'TS_ENUM': "'تعداد'",
    'TS_EQ': "'=='",
    'TS_EVENT': "'حدث'",
    'TS_EXCEPTION': "'استثناء'",
    'TS_EXP': "'**'",
    'TS_EXPORT': "'تصدير'",
    'TS_EXP_ASSIGN': "'**='",
    'TS_EXTENDS': "'يرث-من'",
    'TS_FALSE': "'خاطئ'",
    'TS_FINALLY': "'اخيرا'",
    'TS_FOR': "'حلقة'",
    'TS_FROM': "'من'",
    'TS_FUNCTION': "'دالة'",
    'TS_GET_ELEMENT': "'احضرعنصر'",
    'TS_GET_ELEMENTS': "'احضرعناصر'",
    'TS_GTE': "'>='",
    'TS_IF': "'اذا'",
    'TS_IMPLEMENTS': "'يطبق'",
    'TS_IMPORT': "'استورد'",
    'TS_IN': "'ضمن'",
    'TS_INC': "'++'",
    'TS_INFINITY': "'لانهاية'",
    'TS_INNER_HTML': "'كود-html'",
    'TS_INNER_TEXT': "'النص-الداخلي'",
    'TS_INSTANCEOF': "'عنصر-من'",
    'TS_INTERFACE': "'واجهة'",
    'TS_LET': "'دع'",
    'TS_LISTENER': "'مستمع'",
    'TS_LOCAL_STORAGE': "'تخزين-محلي'",
    'TS_LOG': "'اطبع'",
    'TS_LSH': "'<<'",
    'TS_LTE': "'<='",
    'TS_MAP_KW': "'خريطة'",
    'TS_MOD_ASSIGN': "'%='",
    'TS_MUL_ASSIGN': "'*='",
    'TS_NAN': "'ليس-رقم'",
    'TS_NEQ': "'!='",
    'TS_NEW': "'عنصر-جديد'",
    'TS_NODE': "'عقدة'",
    'TS_NULL': "'غير-موجود'",
    'TS_NULL_ASSIGN': "'??='",
    'TS_NULL_COAL': "'??'",
    'TS_NUMBER_KW': "'عدد'",
    'TS_OBJECT_KW': "'كائن'",
    'TS_OF': "'في'",
    'TS_ON_CHANGE': "'عند-التغيير'",
    'TS_ON_CLICK': "'عند-النقر'",
    'TS_ON_LOAD': "'عند-التحميل'",
    'TS_ON_SUBMIT': "'عند-الارسال'",
    'TS_OR': "'||'",
    'TS_OR_ASSIGN': "'||='",
    'TS_PACKAGE': "'حزمة'",
    'TS_PRIVATE': "'خاص'",
    'TS_PROMPT': "'ادخل'",
    'TS_PROTECTED': "'محمي'",
    'TS_PUBLIC': "'عام'",
    'TS_QUESTION': "'?'",
    'TS_RETURN': "'ارجع'",
    'TS_RSH': "'>>'",
    'TS_SESSION_STORAGE': "'تخزين-جلسة'",
    'TS_SET_KW': "'مجموعة'",
    'TS_SPREAD': "'...'",
    'TS_STATIC': "'صف-ثابت'",
    'TS_STREQ': "'==='",
    'TS_STRING_KW': "'سلسلة'",
    'TS_STRNEQ': "'!=='",
    'TS_STYLE': "'التنسيق'",
    'TS_SUB_ASSIGN': "'-='",
    'TS_SUPER': "'الاب'",
    'TS_SWITCH': "'اختبر'",
    'TS_THIS': "'هذا'",
    'TS_THROW': "'اطلق'",
    'TS_TRUE': "'صحيح'",
    'TS_TRY': "'حاول'",
    'TS_TYPEOF': "'من-نوع'",
    'TS_UNDEFINED': "'غير-معرف'",
    'TS_URSH': "'>>>'",
    'TS_VAR': "'متغير'",
    'TS_WHILE': "'طالما'",
    'TS_WINDOW': "'النافذة'",
}

# Tokens with no single fixed literal — described, not quoted.
TOKEN_DISPLAY_AR_STRUCTURAL = {
    'CLOSE_TAG': "وسم إغلاق (مثل </قسم>)",
    'OPEN_TAG_START': "بداية وسم فتح (مثل <قسم)",
    'IDENTIFIER': "معرف (اسم متغير أو عنصر)",
    'NUMBER': "رقم",
    'CSS_UNIT': "قيمة بوحدة قياس (مثل ٥بكسل أو ٥٠٪)",
    'CSS_HEX_COLOR': "كود لون مثل #ff0000",
    'STRING': "نص محاط بعلامتي تنصيص",
    'WS': "مسافة",
    'BLOCK_COMMENT': "تعليق",
    'LINE_COMMENT': "تعليق",
    'EOF': "نهاية الملف",
    '<EOF>': "نهاية الملف",
}

TOKEN_DISPLAY_AR = {**TOKEN_DISPLAY_AR_GENERATED, **TOKEN_DISPLAY_AR_STRUCTURAL}


def display_for_token_name(name: str) -> str:
    """
    Look up the Arabic display text for an ANTLR symbolic token name.
    Falls back to the raw name (never raises) so a gap in this table
    degrades to something readable rather than crashing the listener.
    """
    name = name.strip()
    return TOKEN_DISPLAY_AR.get(name, name)
